version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: task-management-db
    environment:
      POSTGRES_USER: task_user
      POSTGRES_PASSWORD: task_password
      POSTGRES_DB: task_management_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - task-management-network

volumes:
  pgdata:

networks:
  task-management-network:
    driver: bridge
